# x = 30
# y = 22
# z = 18

# def kattasi(x,y,z):


#     max = x
#     if y > max:
#         max = y
#     elif z >= max:
#         max = z
# print(kattasi)


# a = 30
# b = 222
# c = 1800

# def eng_kattasi(a,b,c):
#     katta = 0
#     if a > b and a >c:
#         katta = a
#     elif b > a and b > c:
#         katta = b
#     else:
#         katta = c 
#     return katta

# x = eng_kattasi

def katta(soz):
    return soz.upper()
soz = "a.u.f"
print(katta(soz))
